# Generated by Django 5.1.1 on 2024-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField()),
                ('credited_on_date', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('irctc_order_no', models.BigIntegerField()),
                ('bank_booking_ref_no', models.BigIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('txn_date', 'credited_on_date', 'irctc_order_no', 'bank_booking_ref_no'), name='unique_bookingdata_constraint')],
            },
        ),
    ]
