# Generated by Django 5.1.1 on 2024-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_bookingdata_unique_bookingdata_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='bank_booking_ref_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='credited_on_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='irctc_order_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='txn_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddConstraint(
            model_name='bookingdata',
            constraint=models.UniqueConstraint(fields=('txn_date', 'credited_on_date', 'irctc_order_no', 'bank_booking_ref_no'), name='unique_bookingdata_constraint'),
        ),
    ]
