# Generated by Django 5.1.1 on 2024-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_bookingdata_bank_booking_ref_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='bank_booking_ref_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='credited_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='irctc_order_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='txn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refunddata',
            name='bank_booking_ref_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refunddata',
            name='bank_refund_ref_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refunddata',
            name='debited_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refunddata',
            name='irctc_order_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refunddata',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
